### ISSUE TITLE
Remove the rectangle from extracted images

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/pdf-annots2json#2]
Right now, the extracted images include the rectangle itself
![image-11-x27-y422](https://user-images.githubusercontent.com/73286100/160094902-4fbf83e6-43e3-4d59-b282-98c50d21f294.jpg)

**Comment by mgmeyers** [comment]
@chrisgrieser So, I looked into this, and it's currently not possible without actually modifying the PDF. If I find a way to do this in the future, I'll let you know, but it's unlikely in the near term.

**Comment by mgmeyers** [comment]
Never mind, was able to figure this out!
