### ISSUE TITLE
Add some info to README

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/pdf-annots2json#3]
- what kind of PDF annotation extraction runs in the background? pdf.js? poppler? pdfminer.six?
- which kinds of annotations exactly are extracted? free text, comments, highlights, underlines, strikethroughs, rectangles?
- some info which release to use for Darwin (arm and amd is not only hard to distinguish, but also requires a bit of googling)

**Comment by mgmeyers** [comment]
Thanks @chrisgrieser, I've added the requested info to the readme!
