### ISSUE TITLE
Rename Release Packages

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/pdf-annots2json#5]
1. please save me from constantly clicking on the wrong release, because the names are barely distinguishable. 😭 
<img width="443" alt="Screenshot 2022-04-08 13 18 17" src="https://user-images.githubusercontent.com/73286100/162425643-df951ec4-df19-4c7e-9669-7b880adcd2ef.png">

2. "darwin" is quite confusing for people not aware that that is the release they should download for Mac

3. please save me from regularly googling this 🙈 
<img width="952" alt="Screenshot 2022-04-08 13 19 58" src="https://user-images.githubusercontent.com/73286100/162425874-b4d9d4f8-3796-4e7b-8739-37bb52d4a85b.png">

---

- "M1 Macs release"
- "Intel Mac release"

...would solve all three problems at once.

**Comment by mgmeyers** [comment]
@chrisgrieser I've attempted to give the release friendlier names, though it turns out GitHub turns non-word characters into periods. But it should be less confusing now.

**Comment by chrisgrieser** [comment]
well, underscores would work, too?

Anyway, it's much better now, thanks! 🙏
