### ISSUE TITLE
FR: use rgb color ranges for the `color` key instead of hex values

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/pdf-annots2json#8]
Reference: https://discord.com/channels/686053708261228577/928964558721265694/962281335135821864

Having, say, a dozen possible values instead of the 256^3 values of hex would make it much easier to build some stuff around highlight color automation.

**Comment by argenos** [comment]
Optionally: settings to define which colours to recognize/use which can also be something customised on most PDF viewers.

**Comment by mgmeyers** [comment]
Annotations now have a `colorCategory` property that's one of:

```
Black
White
Gray
Red
Orange
Yellow
Green
Cyan
Blue
Purple
Magenta
```

It uses the same approach as zotfile. Does this work for your use case?

**Comment by chrisgrieser** [comment]
yeah, I think that should work. 🚀
